version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
    networks:
      - mongo
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "5051:8081"
    volumes:
      - mongo-express:/var/lib/mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    networks:
      - mongo
    depends_on:
      - mongo
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq
      - mongo
  user-service:
    container_name: user-service
    build:
      context: ./FASTAPI-User/app
      dockerfile: Dockerfile
    volumes:
      - ./FASTAPI-User/app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - mongo
      - rabbitmq
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  mongo-express:
  rabbitmq:
