version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  rabbitmq:
    image: rabbitmq:3-management
    ports:    
      - 8080:15672
      - 5672:5672